#!/usr/bin/env python3
"""Copy the content art sheet and derive the renderer manifest after validation."""
import argparse
import hashlib
import json
import shutil
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser()
ap.add_argument('assets', type=Path, help='content assets/map-tiles directory')
a = ap.parse_args()
config = json.loads((ROOT/'pkg/worldmap/map_terrain.json').read_text())
meta = json.loads((a.assets/'terrain-sheet.json').read_text())
expected = {key:i for i,key in enumerate(config['terrains']+['fog','sea'])}
if meta['rows'] != expected or meta['default'] != config['default']:
    raise SystemExit('Terrain mapping differs: regenerate the sheet with the engine config')
if meta['version'] != hashlib.sha256((a.assets/'terrain-sheet.png').read_bytes()).hexdigest()[:12]:
    raise SystemExit('Sheet content hash differs: regenerate the metadata')
out = ROOT/'public/mud-client/public/map-tiles'
out.mkdir(parents=True, exist_ok=True)
shutil.copyfile(a.assets/'terrain-sheet.png', out/'terrain-sheet.png')
(ROOT/'public/mud-client/src/game/widgets/terrainSheet.js').write_text(
    '// Generated by content tools/generate_map_tiles.py; row order from pkg/worldmap/map_terrain.json.\n'
    'export const TERRAIN_SHEET = '+json.dumps(meta,indent=2)+';\n')
print('Synced terrain sheet '+meta['version'])
