
@prod=https://talesofapirate.com/
@local=http://0.0.0.0:8010
@host={{local}}

### this credentials are only for local testing
GET {{host}}/admin/export
Authorization: Basic admin:admin

###
POST {{host}}/admin/import  HTTP/1.1
content-type: application/yaml
Authorization: Basic admin:admin

< import.yml