@prod=https://talesofapirate.com/dnd
@local=http://localhost:8010
@host={{local}}
@token=REPLACE_ME

GET http://localhost:8010/api/items

###

PUT http://localhost:8000/api/createItem/sword_001

###

GET http://localhost:8010/api/item-templates?name=foo&slot=ring2&type=armor

###

POST http://localhost:8000/api/itemTemplates HTTP/1.1
content-type: application/json

 {
    "templateID": "claymore_001",
    "name": "Claymore",
    "description": "A very big sword",
    "itemType": 3,
    "properties": {
      "damageType": "physical",
      "merchantPrice": "5",
      "rarity": "normal",
      "resellPrice": "3"
    },
    "attributes": {
      "damage": "2.5",
      "range": "1.5",
      "strength": "5"
    }
  },