@prod=https://talesofapirate.com/dnd
@local=http://localhost:8010
@host={{local}}
@token=REPLACE_ME

###
GET {{host}}/api/rooms  HTTP/1.1
###
PUT {{host}}/api/rooms/oldtown-entrance  HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

{
    "id": "oldtown-entrance",
    "name": "Entrance to Oldtown ..",
"roomType": "gate",
    "characters": []

},


### 
POST {{host}}/api/rooms  HTTP/1.1
content-type: application/json
authorization: Bearer {{token}}

 {
    "name": "Main Chamber",
    "description": "You reach the Main Chamber of the Catacomb. The noise increases but you can't make out the origin of it.\n",
    "detail": "You look closer to all sides of the room. After a thorough investigation you can see that parts of a wall are made up of loose rocks. You might be able to [move] these rocks.\n",
    "exits": [
        {
            "name": "north",
            "description": "Follow the door to the left",
            "target": "Dungeon001_Entrance"
        },
        {
            "name": "hidden path",
            "hidden": true,
            "description": "You follow the hidden path on the east wall",
            "target": "Dungeon001_End"
        }
    ],
    "actions": [
        {
            "name": "move rocks",
            "description": "You try to move one of the medium sized rocks. Parts of the wall start to crumble and a hidden path opens up."
        }
    ]
},